{
 "title": "Api dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Endpoints", "query": { "query": "label_values(http_route)" } },
   { "name": "percentile", "query": "0.95,0.99" }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status 200",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_route) (floor(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"2..\", http_route=~\"$Endpoints\"}[$__range])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 400",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route) (floor(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"4..\", http_route=~\"$Endpoints\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_route) (floor(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", http_route=~\"$Endpoints\"}[$__range])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 } },
  { "title": "Time series Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Status 200",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (http_route) (floor(increase(http_server_request_duration_seconds_count{http_route=~\"$Endpoints\", http_response_status_code=~\"2..\"}[1m])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 200",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"2..\", http_route=~\"$Endpoints\"}[$__range])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 400",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (http_route) (floor(increase(http_server_request_duration_seconds_count{http_route=~\"$Endpoints\", http_response_status_code=~\"4..\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 400",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"4..\", http_route=~\"$Endpoints\"}[$__range])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (http_route) (floor(increase(http_server_request_duration_seconds_count{http_route=~\"$Endpoints\", http_response_status_code=~\"5..\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", http_route=~\"$Endpoints\"}[$__range])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, \r\n  sum by (http_route, le) (\r\n    rate(http_server_request_duration_seconds_bucket{http_route=~\"$Endpoints\", http_route!=\"\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, \r\n  sum by (http_route, le) (\r\n    rate(http_server_request_duration_seconds_bucket{http_route=~\"$Endpoints\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, \r\n  sum by (http_route, le) (\r\n    rate(http_server_request_duration_seconds_bucket{http_route=~\"$Endpoints\"}[1m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 65 } },
  { "title": "Traces and Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Status 200",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "filters": [
      {
       "id": "31f16c3e",
       "operator": "=~",
       "scope": "span",
       "tag": "http.route",
       "value": [ "$Endpoints" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "",
       "valueType": "duration"
      },
      {
       "id": "24e0fa85",
       "operator": "<",
       "scope": "span",
       "tag": "http.response.status_code",
       "value": [ "300" ],
       "valueType": "int"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Status 400",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "filters": [
      {
       "id": "a4b0d05f",
       "operator": "=~",
       "scope": "span",
       "tag": "http.route",
       "value": [ "$Endpoints" ],
       "valueType": "string"
      },
      {
       "id": "06ae3833",
       "operator": ">",
       "scope": "span",
       "tag": "http.response.status_code",
       "value": [ "399" ]
      },
      {
       "id": "b8c3dc36",
       "operator": "<",
       "scope": "span",
       "tag": "http.response.status_code",
       "value": [ "500" ]
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "filters": [
      {
       "id": "01398f27",
       "operator": "=~",
       "scope": "span",
       "tag": "http.route",
       "value": [ "$Endpoints" ],
       "valueType": "string"
      },
      {
       "id": "68059798",
       "operator": ">",
       "scope": "span",
       "tag": "http.response.status_code",
       "value": [ "499" ],
       "valueType": "int"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "{service_name=\"1.0.0/SkyWorld_IT_Link_API\"}"
    }
   ]
  }
 ]
}